# -*- coding: utf-8 -*-
#
# This file is part of Invenio.
# Copyright (C) 2015-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

addons:
  postgresql: 9.4

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

services:
  - postgresql
  - rabbitmq
  - redis

env:
  global:
    - ES2_DOWNLOAD_URL="https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.4.2/elasticsearch-2.4.2.tar.gz"
    - ES5_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.4.tar.gz"
    - ES_HOST=127.0.0.1
    - SQLALCHEMY_DATABASE_URI="postgresql+psycopg2://postgres@localhost:5432/invenio"
  matrix:
    - REQUIREMENTS=lowest EXTRAS=all,elasticsearch2 ES_URL=$ES2_DOWNLOAD_URL
    - REQUIREMENTS=lowest EXTRAS=all,elasticsearch5 ES_URL=$ES5_DOWNLOAD_URL
    - REQUIREMENTS=release EXTRAS=all,elasticsearch2 ES_URL=$ES2_DOWNLOAD_URL DEPLOY=true
    - REQUIREMENTS=release EXTRAS=all,elasticsearch5 ES_URL=$ES5_DOWNLOAD_URL
    - REQUIREMENTS=devel EXTRAS=all,elasticsearch5 ES_URL=$ES5_DOWNLOAD_URL

python:
  - "2.7"
  - "3.5"

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - "sleep 20"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=dev --req requirements-devel.txt setup.py > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[$EXTRAS]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: lnielsen
  password:
    secure: "b+qTIIt8TMhs8/ZLiiHzvqYrNf2lpEuoxGmMSv8uY5Cq4/vLgnuUwEf9zz7m1bVSpkB63t+tqo7R0WfnnQFhySgJVPXyBJMkKqq6yZec7z0oUXDNjP0St/71LDPmEMI39mJnIPP68jSvkKCwFXHKL8O5S1DBdqyKq1iM5zWO8wikApRuW1NKep7j5sLo706w9af3wKZxEJDOHkAgb+l7TY9zpqlSAhIMDmTSxTYZ5OzV/w4nO+9htl0QGX4OgyLUF923RrbgWh+GxzfgwY3C/+LWpXQl/QWfWTRvaGKJnYEQc72LKzGu3t3eHzTWB1lJDWPE2vDpw4ZL8BGBSxK1771H16/8DiZcF0pgUt130PjFDiTg8xfiw7m0PrOzQRil8x0hgw9gUoLBzRE4EgO1Y+PSJfO/jjUDhX9x0ydjq8/21YK3p1GJJjt5V5ExRPDxethONNot6By6a9Ah5DZfDuQRCSZZ2bKjkKNHuin7K/CqqdtEulUSTuRzu5hxHiR8GpOVMmKXJtL6PRWLW5/2oBXcVtvCG8Qk9Qg5DaxJQ/iVczyCMoYf6hsyrR/I0KOmg/Sx0eUXFOH2vWbDpxm7YnJW9wohHhbyPyEvYYWE1QOj3NCEMoyBpiCZubvSL0weITkM2zTiQBVpoMsduPmxowkLVQ0s1IwyceixKBn07aI="
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "2.7"
    repo: inveniosoftware/invenio-records-rest
    condition: $DEPLOY = true
