{% include 'misc/header.py' %}
notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true
  allow_failures:
    # To allow failures, you need to specify the full environment
    - env: REQUIREMENTS=devel EXTRAS=all,elasticsearch5 ES_URL=$ES5_DOWNLOAD_URL
    - env: REQUIREMENTS=devel EXTRAS=all,elasticsearch6 ES_URL=$ES6_DOWNLOAD_URL

cache:
  - pip

env:
  global:
    - ES5_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.4.tar.gz"
    - ES6_DOWNLOAD_URL="https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.0.tar.gz"
    - ES_HOST=127.0.0.1
  matrix:
    - REQUIREMENTS=lowest EXTRAS=all,elasticsearch5 ES_URL=$ES5_DOWNLOAD_URL
    - REQUIREMENTS=release EXTRAS=all,elasticsearch5 ES_URL=$ES5_DOWNLOAD_URL DEPLOY=true
    - REQUIREMENTS=release EXTRAS=all,elasticsearch6 ES_URL=$ES6_DOWNLOAD_URL
    - REQUIREMENTS=devel EXTRAS=all,elasticsearch5 ES_URL=$ES5_DOWNLOAD_URL
    - REQUIREMENTS=devel EXTRAS=all,elasticsearch6 ES_URL=$ES6_DOWNLOAD_URL

python:
  - "3.5"
  - "3.6"

before_install:
  - "mkdir /tmp/elasticsearch"
  - "wget -O - $ES_URL | tar xz --directory=/tmp/elasticsearch --strip-components=1"
  - "/tmp/elasticsearch/bin/elasticsearch &"
  - "sleep 20"
  - "nvm install 6; nvm use 6"
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e $EXTRAS --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e $EXTRAS --level=pypi setup.py > .travis-release-requirements.txt"


install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[$EXTRAS]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: TODO: PYPIUSERNAME
  password:
    secure: TODO: PYPISECUREHASH
  distributions: "compile_catalog sdist bdist_wheel"
  on:
    tags: true
    python: "3.5"
    repo: {{ cookiecutter.github_repo }}
    condition: $DEPLOY = true
